#!/bin/bash
# 承泽查询系统 - 本地访问脚本
# 请在您的电脑终端运行此脚本

echo "========================================"
echo "承泽查询系统 - 本地访问指南"
echo "========================================"
echo ""

# 检查服务器状态
echo "🔍 检查服务器状态..."
if netstat -tlnp 2>/dev/null | grep -q "10002"; then
    echo "✅ 服务器正在运行"
    echo "📍 端口: 10002"
else
    echo "❌ 服务器未运行"
    echo ""
    echo "请先启动服务器："
    echo "cd /app/workspace/defi-shield/frontend"
    echo "node server.cjs"
    echo ""
    exit 1
fi

echo ""
echo "========================================"
echo "📱 访问方式（请选择一种）"
echo "========================================"
echo ""

echo "【方式 1】本地浏览器访问（推荐）"
echo "----------------------------------------"
echo "1. 打开您的电脑浏览器（Chrome/Firefox/Safari）"
echo "2. 在地址栏输入："
echo ""
echo "   http://localhost:10002"
echo ""
echo "3. 按回车键访问"
echo ""

echo "【方式 2】局域网访问"
echo "----------------------------------------"
echo "如果您的电脑和服务器在同一局域网："
echo ""
echo "1. 查找服务器的局域网 IP："
echo "   - Windows: ipconfig"
echo "   - Mac/Linux: ifconfig"
echo ""
echo "2. 在浏览器输入："
echo "   http://<局域网IP>:10002"
echo ""

echo "【方式 3】公网访问"
echo "----------------------------------------"
echo "如果需要公网访问，请："
echo ""
echo "1. 确保服务器防火墙允许端口 10002"
echo "2. 确保路由器/云服务器已开放端口 10002"
echo "3. 在浏览器输入："
echo "   http://<公网IP>:10002"
echo ""

echo "========================================"
echo "🔧 故障排除"
echo "========================================"
echo ""

echo "【问题 1】打不开网页"
echo "解决方案："
echo "1. 检查服务器是否运行："
echo "   ps aux | grep node"
echo ""
echo "2. 检查端口是否占用："
echo "   netstat -tlnp | grep 10002"
echo ""
echo "3. 重启服务器："
echo "   cd /app/workspace/defi-shield/frontend"
echo "   kill \$(lsof -ti:10002) 2>/dev/null"
echo "   node server.cjs"
echo ""

echo "【问题 2】连接被拒绝"
echo "解决方案："
echo "1. 检查防火墙设置"
echo "2. 确保监听地址是 0.0.0.0"
echo ""

echo "【问题 3】页面空白"
echo "解决方案："
echo "1. 检查浏览器控制台（F12）"
echo "2. 清除浏览器缓存"
echo "3. 尝试无痕模式"
echo ""

echo "========================================"
echo "📞 技术支持"
echo "========================================"
echo ""
echo "如仍有问题，请提供："
echo "1. 浏览器版本"
echo "2. 操作系统版本"
echo "3. 错误信息截图"
echo "4. 服务器日志"
echo ""
echo "========================================"